import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";

import {useForm} from 'react-hook-form'
import { NewFoodForm } from "~/components/NewFoodForm";
import { api } from "~/utils/api";



export default function Home() {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });


  const {data: sessionData} = useSession()


  

  const form = useForm()

  const {register, handleSubmit, formState} = form
  const {errors} = formState




  return (
    <>
      <Head>
        <title>Pandora Fridge</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex  min-h-screen flex-1 flex-col  px-6 py-12 lg:px-8  ">
       <NewFoodForm/>
      </main>
    </>
  );


  
}


